### ISSUE TITLE
Failed on "Getting User's Movie" stage: redis_get_user_data_job_status failed

### ISSUE THREAD

**Issue by TomasCarlson** [sdl60660/letterboxd_recommendations#18]
Can't seem to scrape my profile's movie on any device or network. Seems to be logging "redis_get_user_data_job_status" as failed.

**Comment by jacksongoode** [comment]
I think something in the Letterboxd API likely changed.

**Comment by sdl60660** [comment]
Hello! This was an issue related to a change in the page structure on letterboxd changes (they haven't given me API access so I have to crawl profiles for ratings data). It's been fixed since!
