### ISSUE TITLE
Decade Slider and Genre Exclusion filter

### ISSUE THREAD

**Issue by silvaring** [sdl60660/letterboxd_recommendations#2]
Hi Sam, as per our mail, I think the usefulness of the tool could be increased a lot by having the results be between a decade of the users choosing, as well as excluding all films of a certain 'meta' genre, those being documentary, and animation. I know movielens.org suffers from this same issue, and will often end up recommending you things like 'stand up' comedy specials or documentaries, even though your preferences are clearly for fiction films.

I don't think its necessary to have every genre listed, but I do think documentary and animation should definitely be their own thing when generating a list of results. As for the decade, it makes it a lot easier when doing any serious kind of film research and wanting to get a good vibe for what the highest rated films looked or sounded like for that specific point in time.

**Comment by sdl60660** [comment]
Hi @silvaring! Years will be a lot easier to add than genres with the way the current data is structured, so I'll add that first, but long-term I should be able to get genres in there too:

To do:
- [x] Return full set of recommendations to client
- [x] Attach movie year data to returned recommendations
- [x] Add double-handle UI slider to filter by year
- [x] Write selenium crawler (adapt from other letterboxd project) to grab genre/other content data and attach to recommendation data
- [x] Add UI multi-select for genres

**Comment by silvaring** [comment]
Any updates yet Sam?

I was thinking that since games are my main hobby not movies, are there any chances you could do a similar recommendations program but just for video games? If you need help in sourcing various databases for games I would suggest either avoiding metacritic entirely, or using metacritic in combination with the userreviews and criticsreviews section in [gamefaqs](https://gamefaqs.gamespot.com), which is usually quite comprehensive, for example this very [obscure arcade game](https://gamefaqs.gamespot.com/arcade/567994-jj-squawkers) which very few game historians are aware of but is still pretty noteworthy. It might also be worth considering Steam as an option, but Steam does not have games like the aforementioned and older nintendo games so its mainly suited for PC games.

**Comment by willfolsom** [comment]
I have used this tool a few times (great job, btw), and I was thinking of a way to add filter by genres myself. I took a look at the data but there isn't too much returned to the front end, but just tacking in genre lets you hook up UI check boxes pretty easily. With a little state management you wouldn't even have to refilter every time, but first pass you can just have a function that takes the genre and runs a simple filter.

(hopefully this doesn't sound overly trivializing, still takes some work)

Anyway, if you're open to PRs, I could work something out when time permits and let you take a look. I haven't run it locally yet so that's step 0, and I know scraping LB prodigiously can get you (or your IP at least) banned, so I have to work out how to do both of those things.

Let me know, and great work again.

**Comment by sdl60660** [comment]
Hey! First of all, yes, you're welcome to fork/PR at any time.

That's an interesting way to approach gathering the genre data that I hadn't considered. There's a lot of data, like genre information, on the film pages that only loads with JS, so I was going to build a very slow-moving selenium scraper and just run it over several days. I think you're right that just following the `https://letterboxd.com/films/popular/genre/{genre}/size/small/page/{page_num}/` URL pattern would be a quick and easy way to gather that information. I may have some time to knock this out this week, but again, you're welcome to PR if you want.  For what it's worth, I've had a crawler hit their site with probably 50,000+ requests at this point and haven't been banned, but maybe I've just gotten lucky?

**Comment by sdl60660** [comment]
Hello! This is (finally) resolved on the latest release. You can check it out here: https://letterboxd.samlearner.com/
